spring.application.name=uber

spring.datasource.url=jdbc:mysql://localhost:3306/uberdb
spring.datasource.username=uberuser
spring.datasource.password=uberpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bulatovic.andjelaa@gmail.com
spring.mail.password=zullsggeubtovmjf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:4200
app.backend.url=http://localhost:8080

jwt.public-key: classpath:keys/public.pem
jwt.private-key: classpath:keys/private.pem
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjI2YjEzYWE0MjBjOWE5NDU1YWJlNzI1Y2Q1MjFhMmZmNmQ3NTM0YjcwMzk2NmRlNzBmMDIwZmJlIiwiaCI6Im11cm11cjY0In0=
